added AllProductDatails, SomeProductDetails,  OperationSummary,Opera…
Karpandr/karpandr.github.io pull request #10
Opened 2024-07-19 07:40 UTC by AsligulSafarova

…tionDetails,BasketProducts componnents

2024-07-19 13:39 UTC, Karpandr commented on src/app/OperationDetails/index.tsx
We don't need to implement OperationDetails. It's in "Учет доходов-расходов" project. Out project is "Интернет-магазин".
<img width="1083" alt="image" src="https://github.com/user-attachments/assets/2026d745-c6bb-4bbc-b16c-9a5d43000ed9">

2024-07-19 13:41 UTC, Karpandr commented on src/app/OperationSummary/index.tsx
We don't need to implement OperationSummary. It's in "Учет доходов-расходов" project. Our project is "Интернет-магазин". Remove folder.
![image](https://github.com/user-attachments/assets/3aa4a155-a1d4-4084-9579-7517bbcad773)

2024-07-19 14:26 UTC, AsligulSafarova commented on src/app/OperationSummary/index.tsx
nezametila :)  Учет доходов-расходов.

2024-07-19 14:30 UTC, Karpandr requested changes
Requested changes

2024-07-19 14:30 UTC, Karpandr commented on src/app/AllProductDetails/inde.tsx
Rename folder, file and component to "Product". Rename props to "ProductProps". According to the description of the task product should contain imag**es** rather than one image so please add "images: string[]" property and remove "image" property.

2024-07-19 14:30 UTC, Karpandr commented on src/app/AllProductDetails/inde.tsx
> +
Remove empty line

2024-07-19 14:30 UTC, Karpandr commented on src/app/AllProductDetails/inde.tsx
> +            <Button label="Shop Now" />
In this case we already have existing "Basket" component for "В корзину" button. You can use it with count 0.

2024-07-19 14:30 UTC, Karpandr commented on src/app/AllProductDetails/inde.tsx
After all pending changes in this file create Product.stories file, add some stories. Add Product.module.sass files and some styling to make component good-looking.

2024-07-19 14:30 UTC, Karpandr commented on src/app/AllProductDetails/inde.tsx
> +import Button from 'src/stories/Button';
Remove

2024-07-19 14:30 UTC, Karpandr commented on src/app/BasketProducts/index.tsx
Rename folder, file and component to BasketProduct.

2024-07-19 14:30 UTC, Karpandr commented on src/app/BasketProducts/index.tsx
After all pending changes in this file create BasketProduct.stories file, add some stories. Add BasketProduct.module.sass files and some styling to make component good-looking if necessary.

2024-07-19 14:30 UTC, Karpandr commented on src/app/BasketProducts/index.tsx
> +            <Button label="Delete" />
This "Button" component is implemented as an example in this project. Let's not use it. Use plain <button>.

2024-07-19 14:30 UTC, Karpandr commented on src/app/BasketProducts/index.tsx
> +import Button from 'src/stories/Button';
Remove

2024-07-23 17:16 UTC, AsligulSafarova commented
added produt.stories.ts

2024-07-27 12:34 UTC, AsligulSafarova commented
everything is done  :)

2024-07-29 08:29 UTC, Karpandr commented on src/app/OperationDetails/index.tsx
Removed

2024-07-29 08:31 UTC, Karpandr commented on src/app/ProductCard/ProductCard.tsx
> +
Done

2024-07-29 08:31 UTC, Karpandr commented on src/app/SomeproductDetails/index.tsx
Done

2024-07-29 08:31 UTC, Karpandr commented on src/app/AllProductDetails/inde.tsx
> +
Done

2024-07-29 08:32 UTC, Karpandr commented on src/app/AllProductDetails/inde.tsx
> +
Done

2024-07-29 08:34 UTC, Karpandr commented on src/app/AllProductDetails/inde.tsx
> +            <Button label="Shop Now" />
Done

2024-07-29 08:36 UTC, Karpandr commented on src/app/BasketProducts/index.tsx
> +            <Button label="Delete" />
Done

2024-07-29 08:37 UTC, Karpandr commented on src/app/BasketProducts/index.tsx
> +import Button from 'src/stories/Button';
Done

2024-07-29 09:08 UTC, Karpandr requested changes
Requested changes

2024-07-29 09:08 UTC, Karpandr commented on src/app/Product/Product.module.sass
> +.container
If class exists it should contain some style. Otherwise you can remove it.

2024-07-29 09:08 UTC, Karpandr commented on src/app/BasketProduct/BasketProduct.tsx
Add BasketProduct story

2024-08-02 13:57 UTC, AsligulSafarova commented
Removed container from `product.style` and added all images to the product container

2024-08-02 13:59 UTC, AsligulSafarova commented on src/app/BasketProduct/BasketProduct.tsx
the BasketProduct have story .

2024-08-05 14:13 UTC, Karpandr commented on src/app/AllProductDetails/inde.tsx
Done

2024-08-05 14:13 UTC, Karpandr commented on src/app/AllProductDetails/inde.tsx
> +import Button from 'src/stories/Button';
Done

2024-08-05 14:13 UTC, Karpandr commented on src/app/BasketProducts/index.tsx
Done

2024-08-05 14:13 UTC, Karpandr commented on src/app/Product/Product.tsx
> +      <img src={images[0]} alt={title} />
Done

2024-08-05 14:16 UTC, Karpandr approved these changes
Approved

2024-08-05 14:16 UTC, merged